### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by Emilien-Etadam** [ronilaukkarinen/miniflux-theme-midnight#2]
This theme is awesome, I keep Miniflux because of it. 
But is there a way to add a thumbnail (extracted from the article) before the title ?

**Comment by rollecode** [comment]
Thank you. I'm afraid not via CSS no. You should ask advice in Miniflux repo.

**Comment by Emilien-Etadam** [comment]
Yes I was expecting this answer...but the developer is not agree : https://github.com/miniflux/v2/issues/766

**Comment by rollecode** [comment]
It's clearly a no:

> Sorry, I'm not planning to implement such feature.

There is literally no such thumbnail feature in Miniflux so how do you think I'm able to do it in a theme with CSS only? It is simply not possible to do this on theme-level.

There's only a feed icon (favicon) present in the HTML source. I don't see any article thumbnails built-in in Miniflux so there's nothing to work with. But even if it was, I'm a bit hesitant in including any images to the list view of this theme.

You are free to edit the code however you like, if you figure out something we should include in the repo, please send a pull request. Thanks!

**Comment by Emilien-Etadam** [comment]
Ok I understand, I don't have programming skills...
